import os

runs = ['python eval_covid19china_resnet50.py',
        'python eval_covid19china_resnet101.py',
        'python eval_covid19china_resnext50_32x4d.py',
        'python eval_covid19china_resnext101_32x8d.py',
        'python eval_covid19china_vgg16.py',
        'python eval_covid19china_timm-res2net50_26w_4s.py',
        'python eval_covid19china_densenet121.py',
        'python eval_covid20cases_resnet50.py',
        'python eval_covid20cases_resnet101.py',
        'python eval_covid20cases_resnext50_32x4d.py',
        'python eval_covid20cases_resnext101_32x8d.py',
        'python eval_covid20cases_vgg16.py',
        'python eval_covid20cases_timm-res2net50_26w_4s.py',
        'python eval_covid20cases_densenet121.py',
        'python eval_mosmed_resnet50.py',
        'python eval_mosmed_resnet101.py',
        'python eval_mosmed_resnext50_32x4d.py',
        'python eval_mosmed_resnext101_32x8d.py',
        'python eval_mosmed_vgg16.py',
        'python eval_mosmed_timm-res2net50_26w_4s.py',
        'python eval_mosmed_densenet121.py',
        'python eval_medseg_resnet50.py',
        'python eval_medseg_resnet101.py',
        'python eval_medseg_resnext50_32x4d.py',
        'python eval_medseg_resnext101_32x8d.py',
        'python eval_medseg_vgg16.py',
        'python eval_medseg_timm-res2net50_26w_4s.py',
        'python eval_medseg_densenet121.py',
        'python eval_ricord1a_resnet50.py',
        'python eval_ricord1a_resnet101.py',
        'python eval_ricord1a_resnext50_32x4d.py',
        'python eval_ricord1a_resnext101_32x8d.py',
        'python eval_ricord1a_vgg16.py',
        'python eval_ricord1a_timm-res2net50_26w_4s.py',
        'python eval_ricord1a_densenet121.py']

for run in runs:
  os.system(run)
