import os

ls=["python main.py --configs configs/train_mosmed_unetplusplus_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_mosmed_unet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_mosmed_unet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_mosmed_unet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_mosmed_unet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_mosmed_unet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_mosmed_fpn_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_mosmed_fpn_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_mosmed_fpn_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_mosmed_fpn_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_mosmed_fpn_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_mosmed_linknet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_mosmed_linknet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_mosmed_linknet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_mosmed_linknet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_mosmed_linknet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_mosmed_pan_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_mosmed_pan_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_mosmed_pan_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_mosmed_pan_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_mosmed_pan_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_mosmed_manet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_mosmed_manet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_mosmed_manet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_mosmed_manet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_mosmed_manet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnext101_32x8d_fold4.yml",
]

for l in ls:
  os.system(l)