import os

ls=["python main.py --configs configs/train_covid19china_unetplusplus_densenet121_fold0.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet121_fold1.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet121_fold2.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet121_fold3.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet121_fold4.yml",
"python main.py --configs configs/train_covid19china_unet_densenet121_fold0.yml",
"python main.py --configs configs/train_covid19china_unet_densenet121_fold1.yml",
"python main.py --configs configs/train_covid19china_unet_densenet121_fold2.yml",
"python main.py --configs configs/train_covid19china_unet_densenet121_fold3.yml",
"python main.py --configs configs/train_covid19china_unet_densenet121_fold4.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet121_fold0.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet121_fold1.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet121_fold2.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet121_fold3.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet121_fold4.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet121_fold0.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet121_fold1.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet121_fold2.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet121_fold3.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet121_fold4.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet121_fold0.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet121_fold1.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet121_fold2.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet121_fold3.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet121_fold4.yml",
"python main.py --configs configs/train_covid19china_pan_densenet121_fold0.yml",
"python main.py --configs configs/train_covid19china_pan_densenet121_fold1.yml",
"python main.py --configs configs/train_covid19china_pan_densenet121_fold2.yml",
"python main.py --configs configs/train_covid19china_pan_densenet121_fold3.yml",
"python main.py --configs configs/train_covid19china_pan_densenet121_fold4.yml",
"python main.py --configs configs/train_covid19china_manet_densenet121_fold0.yml",
"python main.py --configs configs/train_covid19china_manet_densenet121_fold1.yml",
"python main.py --configs configs/train_covid19china_manet_densenet121_fold2.yml",
"python main.py --configs configs/train_covid19china_manet_densenet121_fold3.yml",
"python main.py --configs configs/train_covid19china_manet_densenet121_fold4.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_densenet121_fold0.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_densenet121_fold1.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_densenet121_fold2.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_densenet121_fold3.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_densenet121_fold4.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_densenet121_fold0.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_densenet121_fold1.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_densenet121_fold2.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_densenet121_fold3.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_densenet121_fold4.yml",
]

for l in ls:
  os.system(l)