import os

ls=["python main.py --configs configs/train_medseg_unetplusplus_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_medseg_unetplusplus_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_medseg_unetplusplus_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_medseg_unetplusplus_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_medseg_unetplusplus_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_medseg_unet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_medseg_unet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_medseg_unet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_medseg_unet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_medseg_unet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_medseg_fpn_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_medseg_fpn_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_medseg_fpn_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_medseg_fpn_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_medseg_fpn_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_medseg_linknet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_medseg_linknet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_medseg_linknet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_medseg_linknet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_medseg_linknet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_medseg_pan_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_medseg_pan_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_medseg_pan_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_medseg_pan_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_medseg_pan_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_medseg_manet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_medseg_manet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_medseg_manet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_medseg_manet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_medseg_manet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext101_32x8d_fold4.yml",
]

for l in ls:
  os.system(l)