import os

ls=["python main.py --configs configs/train_mosmed_unetplusplus_densenet201_fold0.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_densenet201_fold1.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_densenet201_fold2.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_densenet201_fold3.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_densenet201_fold4.yml",
"python main.py --configs configs/train_mosmed_unet_densenet201_fold0.yml",
"python main.py --configs configs/train_mosmed_unet_densenet201_fold1.yml",
"python main.py --configs configs/train_mosmed_unet_densenet201_fold2.yml",
"python main.py --configs configs/train_mosmed_unet_densenet201_fold3.yml",
"python main.py --configs configs/train_mosmed_unet_densenet201_fold4.yml",
"python main.py --configs configs/train_mosmed_fpn_densenet201_fold0.yml",
"python main.py --configs configs/train_mosmed_fpn_densenet201_fold1.yml",
"python main.py --configs configs/train_mosmed_fpn_densenet201_fold2.yml",
"python main.py --configs configs/train_mosmed_fpn_densenet201_fold3.yml",
"python main.py --configs configs/train_mosmed_fpn_densenet201_fold4.yml",
"python main.py --configs configs/train_mosmed_pspnet_densenet201_fold0.yml",
"python main.py --configs configs/train_mosmed_pspnet_densenet201_fold1.yml",
"python main.py --configs configs/train_mosmed_pspnet_densenet201_fold2.yml",
"python main.py --configs configs/train_mosmed_pspnet_densenet201_fold3.yml",
"python main.py --configs configs/train_mosmed_pspnet_densenet201_fold4.yml",
"python main.py --configs configs/train_mosmed_linknet_densenet201_fold0.yml",
"python main.py --configs configs/train_mosmed_linknet_densenet201_fold1.yml",
"python main.py --configs configs/train_mosmed_linknet_densenet201_fold2.yml",
"python main.py --configs configs/train_mosmed_linknet_densenet201_fold3.yml",
"python main.py --configs configs/train_mosmed_linknet_densenet201_fold4.yml",
"python main.py --configs configs/train_mosmed_manet_densenet201_fold0.yml",
"python main.py --configs configs/train_mosmed_manet_densenet201_fold1.yml",
"python main.py --configs configs/train_mosmed_manet_densenet201_fold2.yml",
"python main.py --configs configs/train_mosmed_manet_densenet201_fold3.yml",
"python main.py --configs configs/train_mosmed_manet_densenet201_fold4.yml",
]

for l in ls:
  os.system(l)