import os

ls=["python main.py --configs configs/train_covid20cases_unetplusplus_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid20cases_unet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid20cases_unet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid20cases_unet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid20cases_unet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid20cases_unet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid20cases_fpn_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid20cases_fpn_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid20cases_fpn_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid20cases_fpn_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid20cases_fpn_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid20cases_pspnet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid20cases_pspnet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid20cases_pspnet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid20cases_pspnet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid20cases_pspnet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid20cases_linknet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid20cases_linknet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid20cases_linknet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid20cases_linknet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid20cases_linknet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid20cases_pan_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid20cases_pan_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid20cases_pan_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid20cases_pan_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid20cases_pan_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid20cases_manet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid20cases_manet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid20cases_manet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid20cases_manet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid20cases_manet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_resnext50_32x4d_fold4.yml",
]

for l in ls:
  os.system(l)