import os

ls=["python main.py --configs configs/train_covid20cases_unetplusplus_vgg16_fold0.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_vgg16_fold1.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_vgg16_fold2.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_vgg16_fold3.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_vgg16_fold4.yml",
"python main.py --configs configs/train_covid20cases_unet_vgg16_fold0.yml",
"python main.py --configs configs/train_covid20cases_unet_vgg16_fold1.yml",
"python main.py --configs configs/train_covid20cases_unet_vgg16_fold2.yml",
"python main.py --configs configs/train_covid20cases_unet_vgg16_fold3.yml",
"python main.py --configs configs/train_covid20cases_unet_vgg16_fold4.yml",
"python main.py --configs configs/train_covid20cases_fpn_vgg16_fold0.yml",
"python main.py --configs configs/train_covid20cases_fpn_vgg16_fold1.yml",
"python main.py --configs configs/train_covid20cases_fpn_vgg16_fold2.yml",
"python main.py --configs configs/train_covid20cases_fpn_vgg16_fold3.yml",
"python main.py --configs configs/train_covid20cases_fpn_vgg16_fold4.yml",
"python main.py --configs configs/train_covid20cases_pspnet_vgg16_fold0.yml",
"python main.py --configs configs/train_covid20cases_pspnet_vgg16_fold1.yml",
"python main.py --configs configs/train_covid20cases_pspnet_vgg16_fold2.yml",
"python main.py --configs configs/train_covid20cases_pspnet_vgg16_fold3.yml",
"python main.py --configs configs/train_covid20cases_pspnet_vgg16_fold4.yml",
"python main.py --configs configs/train_covid20cases_linknet_vgg16_fold0.yml",
"python main.py --configs configs/train_covid20cases_linknet_vgg16_fold1.yml",
"python main.py --configs configs/train_covid20cases_linknet_vgg16_fold2.yml",
"python main.py --configs configs/train_covid20cases_linknet_vgg16_fold3.yml",
"python main.py --configs configs/train_covid20cases_linknet_vgg16_fold4.yml",
"python main.py --configs configs/train_covid20cases_pan_vgg16_fold0.yml",
"python main.py --configs configs/train_covid20cases_pan_vgg16_fold1.yml",
"python main.py --configs configs/train_covid20cases_pan_vgg16_fold2.yml",
"python main.py --configs configs/train_covid20cases_pan_vgg16_fold3.yml",
"python main.py --configs configs/train_covid20cases_pan_vgg16_fold4.yml",
"python main.py --configs configs/train_covid20cases_manet_vgg16_fold0.yml",
"python main.py --configs configs/train_covid20cases_manet_vgg16_fold1.yml",
"python main.py --configs configs/train_covid20cases_manet_vgg16_fold2.yml",
"python main.py --configs configs/train_covid20cases_manet_vgg16_fold3.yml",
"python main.py --configs configs/train_covid20cases_manet_vgg16_fold4.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_vgg16_fold0.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_vgg16_fold1.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_vgg16_fold2.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_vgg16_fold3.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3_vgg16_fold4.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_vgg16_fold0.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_vgg16_fold1.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_vgg16_fold2.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_vgg16_fold3.yml",
"python main.py --configs configs/train_covid20cases_deeplabv3plus_vgg16_fold4.yml",
]

for l in ls:
  os.system(l)