import os

ls=["python main.py --configs configs/train_covid19china_unetplusplus_densenet169_fold0.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet169_fold1.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet169_fold2.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet169_fold3.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet169_fold4.yml",
"python main.py --configs configs/train_covid19china_unet_densenet169_fold0.yml",
"python main.py --configs configs/train_covid19china_unet_densenet169_fold1.yml",
"python main.py --configs configs/train_covid19china_unet_densenet169_fold2.yml",
"python main.py --configs configs/train_covid19china_unet_densenet169_fold3.yml",
"python main.py --configs configs/train_covid19china_unet_densenet169_fold4.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet169_fold0.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet169_fold1.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet169_fold2.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet169_fold3.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet169_fold4.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet169_fold0.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet169_fold1.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet169_fold2.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet169_fold3.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet169_fold4.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet169_fold0.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet169_fold1.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet169_fold2.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet169_fold3.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet169_fold4.yml",
"python main.py --configs configs/train_covid19china_manet_densenet169_fold0.yml",
"python main.py --configs configs/train_covid19china_manet_densenet169_fold1.yml",
"python main.py --configs configs/train_covid19china_manet_densenet169_fold2.yml",
"python main.py --configs configs/train_covid19china_manet_densenet169_fold3.yml",
"python main.py --configs configs/train_covid19china_manet_densenet169_fold4.yml",
]

for l in ls:
  os.system(l)