import os

ls=["python main.py --configs configs/train_covid19china_unet_resnet101_fold0.yml",
"python main.py --configs configs/train_covid19china_unet_resnet101_fold1.yml",
"python main.py --configs configs/train_covid19china_unet_resnet101_fold2.yml",
"python main.py --configs configs/train_covid19china_unet_resnet101_fold3.yml",
"python main.py --configs configs/train_covid19china_unet_resnet101_fold4.yml",
"python main.py --configs configs/train_covid19china_fpn_resnet101_fold0.yml",
"python main.py --configs configs/train_covid19china_fpn_resnet101_fold1.yml",
"python main.py --configs configs/train_covid19china_fpn_resnet101_fold2.yml",
"python main.py --configs configs/train_covid19china_fpn_resnet101_fold3.yml",
"python main.py --configs configs/train_covid19china_fpn_resnet101_fold4.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnet101_fold0.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnet101_fold1.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnet101_fold2.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnet101_fold3.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnet101_fold4.yml",
"python main.py --configs configs/train_covid19china_linknet_resnet101_fold0.yml",
"python main.py --configs configs/train_covid19china_linknet_resnet101_fold1.yml",
"python main.py --configs configs/train_covid19china_linknet_resnet101_fold2.yml",
"python main.py --configs configs/train_covid19china_linknet_resnet101_fold3.yml",
"python main.py --configs configs/train_covid19china_linknet_resnet101_fold4.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_resnet101_fold0.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_resnet101_fold1.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_resnet101_fold2.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_resnet101_fold3.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_resnet101_fold4.yml",
"python main.py --configs configs/train_covid19china_pan_resnet101_fold0.yml",
"python main.py --configs configs/train_covid19china_pan_resnet101_fold1.yml",
"python main.py --configs configs/train_covid19china_pan_resnet101_fold2.yml",
"python main.py --configs configs/train_covid19china_pan_resnet101_fold3.yml",
"python main.py --configs configs/train_covid19china_pan_resnet101_fold4.yml",
"python main.py --configs configs/train_covid19china_manet_resnet101_fold0.yml",
"python main.py --configs configs/train_covid19china_manet_resnet101_fold1.yml",
"python main.py --configs configs/train_covid19china_manet_resnet101_fold2.yml",
"python main.py --configs configs/train_covid19china_manet_resnet101_fold3.yml",
"python main.py --configs configs/train_covid19china_manet_resnet101_fold4.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnet101_fold0.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnet101_fold1.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnet101_fold2.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnet101_fold3.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnet101_fold4.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnet101_fold0.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnet101_fold1.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnet101_fold2.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnet101_fold3.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnet101_fold4.yml",
]

for l in ls:
  os.system(l)