import os

ls=["python main.py --configs configs/train_ricord1a_unetplusplus_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_ricord1a_unetplusplus_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_ricord1a_unetplusplus_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_ricord1a_unetplusplus_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_ricord1a_unetplusplus_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_ricord1a_unet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_ricord1a_unet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_ricord1a_unet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_ricord1a_unet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_ricord1a_unet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_ricord1a_fpn_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_ricord1a_fpn_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_ricord1a_fpn_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_ricord1a_fpn_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_ricord1a_fpn_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_ricord1a_pspnet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_ricord1a_pspnet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_ricord1a_pspnet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_ricord1a_pspnet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_ricord1a_pspnet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_ricord1a_linknet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_ricord1a_linknet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_ricord1a_linknet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_ricord1a_linknet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_ricord1a_linknet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_ricord1a_pan_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_ricord1a_pan_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_ricord1a_pan_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_ricord1a_pan_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_ricord1a_pan_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_ricord1a_manet_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_ricord1a_manet_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_ricord1a_manet_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_ricord1a_manet_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_ricord1a_manet_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_resnext101_32x8d_fold4.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_resnext101_32x8d_fold0.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_resnext101_32x8d_fold1.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_resnext101_32x8d_fold2.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_resnext101_32x8d_fold3.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_resnext101_32x8d_fold4.yml",
]

for l in ls:
  os.system(l)