import os

ls=["python main.py --configs configs/train_covid19china_unetplusplus_densenet201_fold0.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet201_fold1.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet201_fold2.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet201_fold3.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_densenet201_fold4.yml",
"python main.py --configs configs/train_covid19china_unet_densenet201_fold0.yml",
"python main.py --configs configs/train_covid19china_unet_densenet201_fold1.yml",
"python main.py --configs configs/train_covid19china_unet_densenet201_fold2.yml",
"python main.py --configs configs/train_covid19china_unet_densenet201_fold3.yml",
"python main.py --configs configs/train_covid19china_unet_densenet201_fold4.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet201_fold0.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet201_fold1.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet201_fold2.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet201_fold3.yml",
"python main.py --configs configs/train_covid19china_fpn_densenet201_fold4.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet201_fold0.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet201_fold1.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet201_fold2.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet201_fold3.yml",
"python main.py --configs configs/train_covid19china_pspnet_densenet201_fold4.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet201_fold0.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet201_fold1.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet201_fold2.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet201_fold3.yml",
"python main.py --configs configs/train_covid19china_linknet_densenet201_fold4.yml",
"python main.py --configs configs/train_covid19china_manet_densenet201_fold0.yml",
"python main.py --configs configs/train_covid19china_manet_densenet201_fold1.yml",
"python main.py --configs configs/train_covid19china_manet_densenet201_fold2.yml",
"python main.py --configs configs/train_covid19china_manet_densenet201_fold3.yml",
"python main.py --configs configs/train_covid19china_manet_densenet201_fold4.yml",
]

for l in ls:
  os.system(l)