import os

ls=["python main.py --configs configs/train_covid19china_unetplusplus_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid19china_unetplusplus_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid19china_unet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid19china_unet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid19china_unet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid19china_unet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid19china_unet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid19china_fpn_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid19china_fpn_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid19china_fpn_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid19china_fpn_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid19china_fpn_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid19china_pspnet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid19china_linknet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid19china_linknet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid19china_linknet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid19china_linknet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid19china_linknet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid19china_pan_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid19china_pan_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid19china_pan_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid19china_pan_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid19china_pan_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid19china_manet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid19china_manet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid19china_manet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid19china_manet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid19china_manet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid19china_deeplabv3_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_covid19china_deeplabv3plus_resnext50_32x4d_fold4.yml",
]

for l in ls:
  os.system(l)