import os

ls=["python main.py --configs configs/train_mosmed_unet_resnet101_fold0.yml",
"python main.py --configs configs/train_mosmed_unet_resnet101_fold1.yml",
"python main.py --configs configs/train_mosmed_unet_resnet101_fold2.yml",
"python main.py --configs configs/train_mosmed_unet_resnet101_fold3.yml",
"python main.py --configs configs/train_mosmed_unet_resnet101_fold4.yml",
"python main.py --configs configs/train_mosmed_fpn_resnet101_fold0.yml",
"python main.py --configs configs/train_mosmed_fpn_resnet101_fold1.yml",
"python main.py --configs configs/train_mosmed_fpn_resnet101_fold2.yml",
"python main.py --configs configs/train_mosmed_fpn_resnet101_fold3.yml",
"python main.py --configs configs/train_mosmed_fpn_resnet101_fold4.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnet101_fold0.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnet101_fold1.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnet101_fold2.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnet101_fold3.yml",
"python main.py --configs configs/train_mosmed_pspnet_resnet101_fold4.yml",
"python main.py --configs configs/train_mosmed_linknet_resnet101_fold0.yml",
"python main.py --configs configs/train_mosmed_linknet_resnet101_fold1.yml",
"python main.py --configs configs/train_mosmed_linknet_resnet101_fold2.yml",
"python main.py --configs configs/train_mosmed_linknet_resnet101_fold3.yml",
"python main.py --configs configs/train_mosmed_linknet_resnet101_fold4.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_resnet101_fold0.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_resnet101_fold1.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_resnet101_fold2.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_resnet101_fold3.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_resnet101_fold4.yml",
"python main.py --configs configs/train_mosmed_pan_resnet101_fold0.yml",
"python main.py --configs configs/train_mosmed_pan_resnet101_fold1.yml",
"python main.py --configs configs/train_mosmed_pan_resnet101_fold2.yml",
"python main.py --configs configs/train_mosmed_pan_resnet101_fold3.yml",
"python main.py --configs configs/train_mosmed_pan_resnet101_fold4.yml",
"python main.py --configs configs/train_mosmed_manet_resnet101_fold0.yml",
"python main.py --configs configs/train_mosmed_manet_resnet101_fold1.yml",
"python main.py --configs configs/train_mosmed_manet_resnet101_fold2.yml",
"python main.py --configs configs/train_mosmed_manet_resnet101_fold3.yml",
"python main.py --configs configs/train_mosmed_manet_resnet101_fold4.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnet101_fold0.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnet101_fold1.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnet101_fold2.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnet101_fold3.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_resnet101_fold4.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnet101_fold0.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnet101_fold1.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnet101_fold2.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnet101_fold3.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_resnet101_fold4.yml",
]

for l in ls:
  os.system(l)