import os

ls=["python main.py --configs configs/train_medseg_unetplusplus_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_medseg_unetplusplus_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_medseg_unetplusplus_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_medseg_unetplusplus_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_medseg_unetplusplus_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_medseg_unet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_medseg_unet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_medseg_unet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_medseg_unet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_medseg_unet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_medseg_fpn_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_medseg_fpn_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_medseg_fpn_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_medseg_fpn_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_medseg_fpn_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_medseg_pspnet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_medseg_linknet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_medseg_linknet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_medseg_linknet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_medseg_linknet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_medseg_linknet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_medseg_pan_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_medseg_pan_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_medseg_pan_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_medseg_pan_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_medseg_pan_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_medseg_manet_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_medseg_manet_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_medseg_manet_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_medseg_manet_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_medseg_manet_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_medseg_deeplabv3_resnext50_32x4d_fold4.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext50_32x4d_fold0.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext50_32x4d_fold1.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext50_32x4d_fold2.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext50_32x4d_fold3.yml",
"python main.py --configs configs/train_medseg_deeplabv3plus_resnext50_32x4d_fold4.yml",
]

for l in ls:
  os.system(l)