import os

ls=["python main.py --configs configs/train_covid20cases_unetplusplus_se_resnet101_fold0.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_se_resnet101_fold1.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_se_resnet101_fold2.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_se_resnet101_fold3.yml",
"python main.py --configs configs/train_covid20cases_unetplusplus_se_resnet101_fold4.yml",
"python main.py --configs configs/train_covid20cases_unet_se_resnet101_fold0.yml",
"python main.py --configs configs/train_covid20cases_unet_se_resnet101_fold1.yml",
"python main.py --configs configs/train_covid20cases_unet_se_resnet101_fold2.yml",
"python main.py --configs configs/train_covid20cases_unet_se_resnet101_fold3.yml",
"python main.py --configs configs/train_covid20cases_unet_se_resnet101_fold4.yml",
"python main.py --configs configs/train_covid20cases_fpn_se_resnet101_fold0.yml",
"python main.py --configs configs/train_covid20cases_fpn_se_resnet101_fold1.yml",
"python main.py --configs configs/train_covid20cases_fpn_se_resnet101_fold2.yml",
"python main.py --configs configs/train_covid20cases_fpn_se_resnet101_fold3.yml",
"python main.py --configs configs/train_covid20cases_fpn_se_resnet101_fold4.yml",
"python main.py --configs configs/train_covid20cases_pspnet_se_resnet101_fold0.yml",
"python main.py --configs configs/train_covid20cases_pspnet_se_resnet101_fold1.yml",
"python main.py --configs configs/train_covid20cases_pspnet_se_resnet101_fold2.yml",
"python main.py --configs configs/train_covid20cases_pspnet_se_resnet101_fold3.yml",
"python main.py --configs configs/train_covid20cases_pspnet_se_resnet101_fold4.yml",
"python main.py --configs configs/train_covid20cases_linknet_se_resnet101_fold0.yml",
"python main.py --configs configs/train_covid20cases_linknet_se_resnet101_fold1.yml",
"python main.py --configs configs/train_covid20cases_linknet_se_resnet101_fold2.yml",
"python main.py --configs configs/train_covid20cases_linknet_se_resnet101_fold3.yml",
"python main.py --configs configs/train_covid20cases_linknet_se_resnet101_fold4.yml",
"python main.py --configs configs/train_covid20cases_manet_se_resnet101_fold0.yml",
"python main.py --configs configs/train_covid20cases_manet_se_resnet101_fold1.yml",
"python main.py --configs configs/train_covid20cases_manet_se_resnet101_fold2.yml",
"python main.py --configs configs/train_covid20cases_manet_se_resnet101_fold3.yml",
"python main.py --configs configs/train_covid20cases_manet_se_resnet101_fold4.yml",
]

for l in ls:
  os.system(l)