import os

ls=["python main.py --configs configs/train_mosmed_unetplusplus_vgg16_fold0.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_vgg16_fold1.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_vgg16_fold2.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_vgg16_fold3.yml",
"python main.py --configs configs/train_mosmed_unetplusplus_vgg16_fold4.yml",
"python main.py --configs configs/train_mosmed_unet_vgg16_fold0.yml",
"python main.py --configs configs/train_mosmed_unet_vgg16_fold1.yml",
"python main.py --configs configs/train_mosmed_unet_vgg16_fold2.yml",
"python main.py --configs configs/train_mosmed_unet_vgg16_fold3.yml",
"python main.py --configs configs/train_mosmed_unet_vgg16_fold4.yml",
"python main.py --configs configs/train_mosmed_fpn_vgg16_fold0.yml",
"python main.py --configs configs/train_mosmed_fpn_vgg16_fold1.yml",
"python main.py --configs configs/train_mosmed_fpn_vgg16_fold2.yml",
"python main.py --configs configs/train_mosmed_fpn_vgg16_fold3.yml",
"python main.py --configs configs/train_mosmed_fpn_vgg16_fold4.yml",
"python main.py --configs configs/train_mosmed_pspnet_vgg16_fold0.yml",
"python main.py --configs configs/train_mosmed_pspnet_vgg16_fold1.yml",
"python main.py --configs configs/train_mosmed_pspnet_vgg16_fold2.yml",
"python main.py --configs configs/train_mosmed_pspnet_vgg16_fold3.yml",
"python main.py --configs configs/train_mosmed_pspnet_vgg16_fold4.yml",
"python main.py --configs configs/train_mosmed_linknet_vgg16_fold0.yml",
"python main.py --configs configs/train_mosmed_linknet_vgg16_fold1.yml",
"python main.py --configs configs/train_mosmed_linknet_vgg16_fold2.yml",
"python main.py --configs configs/train_mosmed_linknet_vgg16_fold3.yml",
"python main.py --configs configs/train_mosmed_linknet_vgg16_fold4.yml",
"python main.py --configs configs/train_mosmed_pan_vgg16_fold0.yml",
"python main.py --configs configs/train_mosmed_pan_vgg16_fold1.yml",
"python main.py --configs configs/train_mosmed_pan_vgg16_fold2.yml",
"python main.py --configs configs/train_mosmed_pan_vgg16_fold3.yml",
"python main.py --configs configs/train_mosmed_pan_vgg16_fold4.yml",
"python main.py --configs configs/train_mosmed_manet_vgg16_fold0.yml",
"python main.py --configs configs/train_mosmed_manet_vgg16_fold1.yml",
"python main.py --configs configs/train_mosmed_manet_vgg16_fold2.yml",
"python main.py --configs configs/train_mosmed_manet_vgg16_fold3.yml",
"python main.py --configs configs/train_mosmed_manet_vgg16_fold4.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_vgg16_fold0.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_vgg16_fold1.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_vgg16_fold2.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_vgg16_fold3.yml",
"python main.py --configs configs/train_mosmed_deeplabv3_vgg16_fold4.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_vgg16_fold0.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_vgg16_fold1.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_vgg16_fold2.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_vgg16_fold3.yml",
"python main.py --configs configs/train_mosmed_deeplabv3plus_vgg16_fold4.yml",
]

for l in ls:
  os.system(l)