import os

ls=["python main.py --configs configs/train_ricord1a_unetplusplus_timm-res2net50_26w_4s_fold0.yml",
"python main.py --configs configs/train_ricord1a_unetplusplus_timm-res2net50_26w_4s_fold1.yml",
"python main.py --configs configs/train_ricord1a_unetplusplus_timm-res2net50_26w_4s_fold2.yml",
"python main.py --configs configs/train_ricord1a_unetplusplus_timm-res2net50_26w_4s_fold3.yml",
"python main.py --configs configs/train_ricord1a_unetplusplus_timm-res2net50_26w_4s_fold4.yml",
"python main.py --configs configs/train_ricord1a_unet_timm-res2net50_26w_4s_fold0.yml",
"python main.py --configs configs/train_ricord1a_unet_timm-res2net50_26w_4s_fold1.yml",
"python main.py --configs configs/train_ricord1a_unet_timm-res2net50_26w_4s_fold2.yml",
"python main.py --configs configs/train_ricord1a_unet_timm-res2net50_26w_4s_fold3.yml",
"python main.py --configs configs/train_ricord1a_unet_timm-res2net50_26w_4s_fold4.yml",
"python main.py --configs configs/train_ricord1a_fpn_timm-res2net50_26w_4s_fold0.yml",
"python main.py --configs configs/train_ricord1a_fpn_timm-res2net50_26w_4s_fold1.yml",
"python main.py --configs configs/train_ricord1a_fpn_timm-res2net50_26w_4s_fold2.yml",
"python main.py --configs configs/train_ricord1a_fpn_timm-res2net50_26w_4s_fold3.yml",
"python main.py --configs configs/train_ricord1a_fpn_timm-res2net50_26w_4s_fold4.yml",
"python main.py --configs configs/train_ricord1a_pspnet_timm-res2net50_26w_4s_fold0.yml",
"python main.py --configs configs/train_ricord1a_pspnet_timm-res2net50_26w_4s_fold1.yml",
"python main.py --configs configs/train_ricord1a_pspnet_timm-res2net50_26w_4s_fold2.yml",
"python main.py --configs configs/train_ricord1a_pspnet_timm-res2net50_26w_4s_fold3.yml",
"python main.py --configs configs/train_ricord1a_pspnet_timm-res2net50_26w_4s_fold4.yml",
"python main.py --configs configs/train_ricord1a_linknet_timm-res2net50_26w_4s_fold0.yml",
"python main.py --configs configs/train_ricord1a_linknet_timm-res2net50_26w_4s_fold1.yml",
"python main.py --configs configs/train_ricord1a_linknet_timm-res2net50_26w_4s_fold2.yml",
"python main.py --configs configs/train_ricord1a_linknet_timm-res2net50_26w_4s_fold3.yml",
"python main.py --configs configs/train_ricord1a_linknet_timm-res2net50_26w_4s_fold4.yml",
"python main.py --configs configs/train_ricord1a_pan_timm-res2net50_26w_4s_fold0.yml",
"python main.py --configs configs/train_ricord1a_pan_timm-res2net50_26w_4s_fold1.yml",
"python main.py --configs configs/train_ricord1a_pan_timm-res2net50_26w_4s_fold2.yml",
"python main.py --configs configs/train_ricord1a_pan_timm-res2net50_26w_4s_fold3.yml",
"python main.py --configs configs/train_ricord1a_pan_timm-res2net50_26w_4s_fold4.yml",
"python main.py --configs configs/train_ricord1a_manet_timm-res2net50_26w_4s_fold0.yml",
"python main.py --configs configs/train_ricord1a_manet_timm-res2net50_26w_4s_fold1.yml",
"python main.py --configs configs/train_ricord1a_manet_timm-res2net50_26w_4s_fold2.yml",
"python main.py --configs configs/train_ricord1a_manet_timm-res2net50_26w_4s_fold3.yml",
"python main.py --configs configs/train_ricord1a_manet_timm-res2net50_26w_4s_fold4.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_timm-res2net50_26w_4s_fold0.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_timm-res2net50_26w_4s_fold1.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_timm-res2net50_26w_4s_fold2.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_timm-res2net50_26w_4s_fold3.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3_timm-res2net50_26w_4s_fold4.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_timm-res2net50_26w_4s_fold0.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_timm-res2net50_26w_4s_fold1.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_timm-res2net50_26w_4s_fold2.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_timm-res2net50_26w_4s_fold3.yml",
"python main.py --configs configs/train_ricord1a_deeplabv3plus_timm-res2net50_26w_4s_fold4.yml",
]

for l in ls:
  os.system(l)